# -*- coding: utf-8 -*-
"""Calculadora ELO (streamlit).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QxQy_UWtla1Kk4Zx_eb9DTqR30faFjHC
"""



import streamlit as st

def calculate_probability(ELO_mandante, ELO_visitante):
    p = (ELO_mandante / 400) / ((ELO_mandante / 400) + (ELO_visitante / 400))
    return p

def main():
    st.title("Cálculo da Probabilidade de Vitória")
    st.write("Este aplicativo calcula a probabilidade de vitória de um time com base em seus ratings ELO.")

    # Input ELO_mandante and ELO_visitante values
    ELO_mandante = st.number_input("Informe o rating ELO do time da casa: ", min_value=0)
    ELO_visitante = st.number_input("Informe o rating ELO do time visitante: ", min_value=0)

    # Calculate the probability of victory
    probability = calculate_probability(ELO_mandante, ELO_visitante)

    st.write(f"A probabilidade do time da casa vencer é: {probability:.2%}")

     # Exibe o crédito do desenvolvedor
    st.write("Desenvolvido por Lyssandro Silveira")


if __name__ == '__main__':
    main()
